#!/bin/bash

# avoid full rebuild if script is runs from symlinked location
cd $(readlink -f $(dirname $0))

./buildt
rm CMakeCache.txt
cmake ${1} . \
 -DCMAKE_BUILD_TYPE='Debug' \
 -DCMAKE_INSTALL_PREFIX=/usr \
 -DCMAKE_CXX_STANDARD="11" \
 && make ${2}
