/* config.h. Generated by cmake from config.h.cmake */

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT ${SIZEOF_INT}

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG ${SIZEOF_LONG}

/* is 1 if the system has stdint.h */
#cmakedefine HAVE_STDINT_H 1

/* is 1 if the system has strings.h */
#cmakedefine HAVE_STRINGS_H 1

/* is 1 if the system has unistd.h */
#cmakedefine HAVE_UNISTD_H 1
